package kkreiju.moosicplayer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Arjay
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    Songs songs = new Songs();
    Timer timer = new Timer(1000, this);
    int i = 0;
    int minute = 0;
    int second = 0;
    boolean onLoop = false;

    //uninitialized music art
    ImageIcon noMusicArt = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\icon.png");
    Image scalednoMusicArt = noMusicArt.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);

    //TEXTURES
    ImageIcon noplayButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\play.png");
    Image scaledPlayButton = noplayButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon nopauseButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\pause.png");
    Image scaledPauseButton = nopauseButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon noloopinactiveButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\notOnLoop.png");
    Image scaledLoopInactiveButton = noloopinactiveButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon noloopactiveButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\onLoop.png");
    Image scaledLoopActiveButton = noloopactiveButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon nopreviousButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\previous.png");
    Image scaledPreviousButton = nopreviousButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon nonextButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\next.png");
    Image scaledNextButton = nonextButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);
    ImageIcon noshuffleButton = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\shuffle.png");
    Image scaledShuffleButton = noshuffleButton.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH);

    /**
     * Creates new form GUI
     */
    public GUI() {
        ImageIcon icon = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\icon.png");
        setIconImage(icon.getImage());
        initComponents();
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        musicSlider.setMaximum(songs.calculateTime);
        if (i < songs.calculateTime) {
            musicSlider.setValue(i);
            second++;
        } else {
            timer.stop();
            playButton.setIcon(new javax.swing.ImageIcon(scaledPlayButton));
            songs.hasStarted = false;
            songs.clip = null;
            songs.setIsPlaying(false);
        }

        if (second > 59) {
            second = 0;
            minute++;
        }

        String s = "" + second;
        i++;
        if (s.length() == 1) {
            s = "0".concat(s);
        }
        startingTime.setText(minute + ":" + s);

        if (!timer.isRunning()) {
            i = 0;
            second = 0;
            minute = 0;
            if (onLoop) {
                playMethod();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        startingTime = new javax.swing.JLabel();
        musicSlider = new javax.swing.JSlider();
        endingTime = new javax.swing.JLabel();
        playButton = new javax.swing.JLabel();
        loopButton = new javax.swing.JLabel();
        shuffleButton = new javax.swing.JLabel();
        previousButton = new javax.swing.JLabel();
        nextImageButton = new javax.swing.JLabel();
        actionLog = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        musicTitle = new javax.swing.JLabel();
        artistName = new javax.swing.JLabel();
        coverArt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 560));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(439, 61));
        jPanel2.setMinimumSize(new java.awt.Dimension(439, 61));

        startingTime.setForeground(new java.awt.Color(255, 255, 255));
        startingTime.setText("--:--");

        musicSlider.setBackground(new java.awt.Color(102, 102, 102));
        musicSlider.setValue(0);
        musicSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        musicSlider.setEnabled(false);
        musicSlider.setMaximumSize(new java.awt.Dimension(200, 20));
        musicSlider.setMinimumSize(new java.awt.Dimension(200, 20));
        musicSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                musicSliderStateChanged(evt);
            }
        });
        musicSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicSliderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musicSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                musicSliderMouseReleased(evt);
            }
        });
        musicSlider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                musicSliderKeyPressed(evt);
            }
        });

        endingTime.setForeground(new java.awt.Color(255, 255, 255));
        endingTime.setText("--:--");

        playButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playButton.setIcon(new javax.swing.ImageIcon(scaledPlayButton));
        playButton.setText("");
        playButton.setMaximumSize(new java.awt.Dimension(25, 25));
        playButton.setMinimumSize(new java.awt.Dimension(25, 25));
        playButton.setPreferredSize(new java.awt.Dimension(25, 25));
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        loopButton.setIcon(new javax.swing.ImageIcon(scaledLoopInactiveButton));
        loopButton.setText("");
        loopButton.setMaximumSize(new java.awt.Dimension(25, 25));
        loopButton.setMinimumSize(new java.awt.Dimension(25, 25));
        loopButton.setPreferredSize(new java.awt.Dimension(25, 25));
        loopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loopButtonMouseClicked(evt);
            }
        });

        shuffleButton.setIcon(new javax.swing.ImageIcon(scaledShuffleButton));
        shuffleButton.setText("");
        shuffleButton.setMaximumSize(new java.awt.Dimension(25, 25));
        shuffleButton.setMinimumSize(new java.awt.Dimension(25, 25));
        shuffleButton.setPreferredSize(new java.awt.Dimension(25, 25));
        shuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shuffleButtonMouseClicked(evt);
            }
        });

        previousButton.setIcon(new javax.swing.ImageIcon(scaledPreviousButton));
        previousButton.setText("");
        previousButton.setMaximumSize(new java.awt.Dimension(25, 25));
        previousButton.setMinimumSize(new java.awt.Dimension(25, 25));
        previousButton.setPreferredSize(new java.awt.Dimension(25, 25));
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });

        nextImageButton.setIcon(new javax.swing.ImageIcon(scaledNextButton));
        nextImageButton.setText("");
        nextImageButton.setMaximumSize(new java.awt.Dimension(25, 25));
        nextImageButton.setMinimumSize(new java.awt.Dimension(25, 25));
        nextImageButton.setPreferredSize(new java.awt.Dimension(25, 25));
        nextImageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextImageButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(nextImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(startingTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(loopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(endingTime, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(musicSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startingTime)
                    .addComponent(endingTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(musicSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        actionLog.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        actionLog.setForeground(new java.awt.Color(255, 255, 255));
        actionLog.setText("Action Log:");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        musicTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        musicTitle.setForeground(new java.awt.Color(255, 255, 255));
        musicTitle.setText("Music Title");

        artistName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        artistName.setForeground(new java.awt.Color(255, 255, 255));
        artistName.setText("Artist Name");

        coverArt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coverArt.setIcon(new javax.swing.ImageIcon(scalednoMusicArt));
        coverArt.setText("");
        coverArt.setMaximumSize(new java.awt.Dimension(120, 120));
        coverArt.setMinimumSize(new java.awt.Dimension(120, 120));
        coverArt.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(coverArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(musicTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(artistName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coverArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(actionLog, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(actionLog))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        playMethod();
    }//GEN-LAST:event_playButtonMouseClicked

    private void loopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loopButtonMouseClicked
        if (onLoop) {
            onLoop = false;
            loopButton.setText("Loop");
            loopButton.setIcon(new javax.swing.ImageIcon(scaledLoopInactiveButton));
        } else {
            onLoop = true;
            loopButton.setText("On Repeat");
            loopButton.setIcon(new javax.swing.ImageIcon(scaledLoopActiveButton));
        }
        actionLog.setText("Action Log: Loop");
    }//GEN-LAST:event_loopButtonMouseClicked

    private void shuffleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shuffleButtonMouseClicked
        actionLog.setText("Action Log: Shuffled");
    }//GEN-LAST:event_shuffleButtonMouseClicked

    private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked
        actionLog.setText("Action Log: Previous");
    }//GEN-LAST:event_previousButtonMouseClicked

    private void nextImageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageButtonMouseClicked
        actionLog.setText("Action Log: Next");
    }//GEN-LAST:event_nextImageButtonMouseClicked

    private void musicSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicSliderMousePressed
        if (timer.isRunning()) {
            timer.stop();
        }
    }//GEN-LAST:event_musicSliderMousePressed

    private void musicSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_musicSliderStateChanged
        minute = musicSlider.getValue() / 60;
        second = musicSlider.getValue() % 60;
        String s = "" + second;
        if (s.length() == 1) {
            s = "0".concat(s);
        }
        startingTime.setText(minute + ":" + s);
    }//GEN-LAST:event_musicSliderStateChanged

    private void musicSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicSliderMouseReleased
        if (!timer.isRunning() && songs.getIsPlaying()) {
            timer.start();
        }
        i = musicSlider.getValue();
        minute = musicSlider.getValue() / 60;
        second = musicSlider.getValue() % 60;
        String s = "" + second;
        if (s.length() == 1) {
            s = "0".concat(s);
        }
        startingTime.setText(minute + ":" + s);
        songs.changeTime = i * 1_000_000;
        songs.hasStarted = true;
        if(songs.getIsPlaying()){
            songs.ChangeValue();
        }
    }//GEN-LAST:event_musicSliderMouseReleased

    private void musicSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicSliderMouseExited

    }//GEN-LAST:event_musicSliderMouseExited

    // I DELETED THE INITCOMPONENTS FUNCTIONS NOW WHAT HAVE I DONE HUHU ANYWAY AYAW HILABTI!
    private void formKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void playButtonKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void musicSliderKeyPressed(java.awt.event.KeyEvent evt) {

    }

    public void playMethod() {
        if (!songs.hasStarted) {
            startingTime.setText("0:00");
            musicSlider.setValue(0);
            timer.start();
            musicSlider.setEnabled(true);
        }
        songs.Play();

        musicTitle.setText("Come Inside of My Heart");
        artistName.setText("IV of Spades");

        //COVER ART
        ImageIcon ca = new ImageIcon("src\\main\\java\\kkreiju\\moosicplayer\\textures\\coverarts\\come inside of my heart.jpg");
        Image scImg = ca.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        coverArt.setIcon(new javax.swing.ImageIcon(scImg));

        endingTime.setText(songs.displayEndTime);
        if (songs.getIsPlaying()) {
            actionLog.setText("Action Log: Played");
            playButton.setIcon(new javax.swing.ImageIcon(scaledPauseButton));
            if(songs.clip.getMicrosecondPosition() == 0){
                songs.clip.setMicrosecondPosition(0);
            }
            else if(songs.clip.getMicrosecondPosition() != songs.changeTime && !onLoop){
                songs.clip.setMicrosecondPosition(songs.changeTime);
            }
            if (!timer.isRunning()) {
                timer.start();
            }
        } else {
            actionLog.setText("Action Log: Paused");
            playButton.setIcon(new javax.swing.ImageIcon(scaledPlayButton));
            if (timer.isRunning()) {
                timer.stop();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLog;
    private javax.swing.JLabel artistName;
    private javax.swing.JLabel coverArt;
    private javax.swing.JLabel endingTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loopButton;
    public javax.swing.JSlider musicSlider;
    private javax.swing.JLabel musicTitle;
    private javax.swing.JLabel nextImageButton;
    private javax.swing.JLabel playButton;
    private javax.swing.JLabel previousButton;
    private javax.swing.JLabel shuffleButton;
    private javax.swing.JLabel startingTime;
    // End of variables declaration//GEN-END:variables
}
