/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/File.java to edit this template
 */
package kkreiju.moosicplayer;

/**
 *
 * @author Arjay
 */
public class Lyrics {

    String lyrics;

    public void Always() {
        lyrics = "<html><center>Baby, baby<br>"
                + "There will always be<br>"
                + "A space for you and me<br>"
                + "Right where you left it<br>"
                + "And just maybe<br>"
                + "Enough time will pass<br>"
                + "We'll look back and laugh<br>"
                + "Just don't forget it<br><br>"
                + "And maybe I'm wrong<br>"
                + "For writing this song<br>"
                + "Losing my head over you<br><br>"
                + "And I'll be here<br>"
                + "Because we both know how it goes<br>"
                + "I don't want things to change<br>"
                + "I pray they stay the same, always<br>"
                + "And I don't care<br>"
                + "If you're with somebody else<br>"
                + "I'll give you time and space<br>"
                + "Just know I'm not a phase<br>"
                + "I'm always-ways-ways<br>"
                + "Always-ways-ways<br>"
                + "I'm always-ways-ways<br><br>"
                + "Pretty lady<br>"
                + "Used to walk with me<br>"
                + "Down Bloor street<br>"
                + "Oh, what a time<br>"
                + "And I still remember the fussing, the fighting<br>"
                + "The f*cking, the lying<br>"
                + "It's all fine<br>"
                + "You'll always be mine<br><br>"
                + "And maybe I'm wrong<br>"
                + "For writing this song<br>"
                + "Losing my head over you<br><br>"
                + "And I'll be here<br>"
                + "Because we both know how it goes<br>"
                + "I don't want things to change<br>"
                + "I pray they stay the same, always<br>"
                + "And I don't care<br>"
                + "If you're with somebody else<br>"
                + "I'll give you time and space<br>"
                + "Just know I'm not a phase<br>"
                + "I'm always-ways-ways<br>"
                + "Always-ways-ways<br>"
                + "I'm always-ways-ways<br><br>"
                + "Always<br>"
                + "Can count on it sure as the stars in the sky<br>"
                + "Always<br>"
                + "You can count on it sure as the sun will rise<br>"
                + "Always<br>"
                + "My love for you ain't going nowhere<br>"
                + "Always<br>"
                + "I will be here</center></html>";
    }

    public void ComeInsideOfMyHeart() {
        lyrics = "<html><center>I love you<br>"
                + "But I don't really show you<br>"
                + "I'd call you<br>"
                + "But only if you want me too<br><br>"
                + "Oh don't you let it stop<br>"
                + "Oh I won't let it happen baby<br>"
                + "I will never stop<br>"
                + "But only if you listen to me<br><br>"
                + "Come inside of my heart<br>"
                + "If you're looking for answers<br>"
                + "Look at the stars<br>"
                + "Go a little bit faster<br>"
                + "Ooh ooh ooh<br><br>"
                + "Oh baby<br>"
                + "Forgive me if I hurt you<br>"
                + "Come save me<br>"
                + "'Cause you're the only one for me<br><br>"
                + "Oh don't you let it stop<br>"
                + "Oh I won't let it happen baby<br>"
                + "I will never stop<br>"
                + "But only if you listen to me<br><br>"
                + "Come inside of my heart<br>"
                + "If you're looking for answers<br>"
                + "Look at the stars<br>"
                + "Go a little bit faster<br>"
                + "Ooh ooh ooh<br><br>"
                + "Come inside of my heart<br>"
                + "If you're looking for answers<br>"
                + "Look at the stars<br>"
                + "Go a little bit faster<br>"
                + "Ooh ooh ooh<br><br>"
                + "Whatever happens to me baby<br>"
                + "I'm sorry<br>"
                + "No one could ever go my way<br><br>"
                + "I love you but I don't really show you<br><br>"
                + "Come inside of my heart<br>"
                + "If you're looking for answers<br>"
                + "Look at the stars<br>"
                + "Go a little bit faster<br>"
                + "Ooh ooh ooh<br><br>"
                + "Come inside of my heart<br>"
                + "If you're looking for answers<br>"
                + "Look at the stars<br>"
                + "Go a little bit faster<br>"
                + "Ooh ooh ooh<br><br></center></html>";
    }

    public void Disenchanted() {
        lyrics = "<html><center>Well, I was there on the day they sold the cause<br>for the queen<br>"
                + "And when the lights all went out, we watched our<br>lives on the screen<br>"
                + "I hate the ending myself, but it started with<br>an alright scene<br><br>"
                + "It was the roar of the crowd that<br>gave me heartache to sing<br>"
                + "It was a lie when they smiled and said,<br>\"You won't feel a thing\"<br>"
                + "And as we ran from the cops we laughed so hard,<br>it would sting<br>"
                + "Yeah, yeah, whoa<br><br>"
                + "If I'm so wrong<br>"
                + "How can you listen all night long?<br>"
                + "Now, will it matter after I'm gone?<br>"
                + "Because you never learned a goddamn thing<br><br>"
                + "You're just a sad song with nothing to say<br>"
                + "About a lifelong wait for a hospital stay<br>"
                + "And if you think that I'm wrong<br>"
                + "This never meant nothing to you<br><br>"
                + "I spent my high school career spit on and<br> shoved to agree<br>"
                + "So I could watch all my heroes sell a car on TV<br>"
                + "Bring out the old guillotine, we'll show<br>them what we all mean<br>"
                + "Yeah, yeah, whoa<br><br>"
                + "If I'm so wrong<br>"
                + "How can you listen all night long?<br>"
                + "Now, will it matter after I'm gone?<br>"
                + "Because you never learned a goddamn thing<br><br>"
                + "You're just a sad song with nothing to say<br>"
                + "About a lifelong wait for a hospital stay<br>"
                + "And if you think that I'm wrong<br>"
                + "This never meant nothing to you<br><br>"
                + "So go, go away<br>"
                + "Just go, run away<br>"
                + "But where did you run to? And where did you hide?<br>"
                + "Go find another way, price you pay<br><br>"
                + "Whoa, whoa, whoa, whoa<br>"
                + "Whoa, whoa, whoa, whoa!<br><br>"
                + "You're just a sad song with nothing to say<br>"
                + "About a lifelong wait for a hospital stay<br>"
                + "And if you think that I'm wrong<br>"
                + "This never meant nothing to you, come on!<br>"
                + "You're just a sad song with nothing to say<br>"
                + "About a lifelong wait for a hospital stay<br>"
                + "And if you think that I'm wrong<br>"
                + "This never meant nothing to you<br><br>"
                + "At all, at all<br>"
                + "At all, at all</center></html>";
    }

    public void Enchanted() {
        lyrics = "<html><center>There I was again tonight<br>"
                + "Forcing laughter, faking smiles<br>"
                + "Same old tired, lonely place<br>"
                + "Walls of insincerity<br>"
                + "Shifting eyes and vacancy<br>"
                + "Vanished when I saw your face<br>"
                + "All I can say is it was enchanting to meet you<br><br>"
                + "Your eyes whispered, \"Have we met?\"<br>"
                + "Across the room, your silhouette<br>"
                + "Starts to make its way to me<br>"
                + "The playful conversation starts<br>"
                + "Counter all your quick remarks<br>"
                + "Like passing notes in secrecy<br>"
                + "And it was enchanting to meet you<br>"
                + "All I can say is I was enchanted to meet you<br><br>"
                + "This night is sparklin', don't you let it go<br>"
                + "I'm wonderstruck, blushin' all the way home<br>"
                + "I'll spend forever wonderin' if you knew<br>"
                + "I was enchanted to meet you<br><br>"
                + "The lingering question kept me up<br>"
                + "2AM, who do you love?<br>"
                + "I wonder 'til I'm wide awake<br>"
                + "And now, I'm pacing back and forth<br>"
                + "Wishing you were at my door<br>"
                + "I'd open up and you would say<br>"
                + "\"Hey, it was enchanting to meet you\"<br>"
                + "All I know is I was enchanted to meet you<br><br>"
                + "This night is sparklin', don't you let it go<br>"
                + "I'm wonderstruck, blushin' all the way home<br>"
                + "I'll spend forever wonderin' if you knew<br>"
                + "This night is flawless, don't you let it go<br>"
                + "I'm wonderstruck, dancing around all alone<br>"
                + "I'll spend forever wonderin' if you knew<br>"
                + "I was enchanted to meet you<br><br>"
                + "This is me praying that<br>"
                + "This was the very first page<br>"
                + "Not where the storyline ends<br>"
                + "My thoughts will echo your name<br>"
                + "Until I see you again<br>"
                + "These are the words I held back<br>"
                + "As I was leaving too soon<br>"
                + "I was enchanted to meet you<br>"
                + "Please, don't be in love with someone else<br>"
                + "Please, don't have somebody waiting on you<br>"
                + "Please, don't be in love with someone else<br>"
                + "Please, don't have somebody waiting on you <br><br>"
                + "This night is sparklin', don't you let it go<br>"
                + "I'm wonderstruck, blushin' all the way home<br>"
                + "I'll spend forever wonderin' if you knew<br>"
                + "This night is flawless, don't you let it go<br>"
                + "I'm wonderstruck, dancing around all alone<br>"
                + "I'll spend forever wonderin' if you knew<br>"
                + "I was enchanted to meet you<br><br>"
                + "Please, don't be in love with someone else<br>"
                + "Please, don't have somebody waiting on you</center></html>";
    }

    public void Fallen() {
        lyrics = "<html><center>What if I told you that I've fallen?<br>"
                + "And I like the way you say my name<br>"
                + "My heart skips a beat when I hear you calling<br>"
                + "And I like that it won't go away<br><br>"
                + "But never mind, don't wanna give you any trouble<br>"
                + "Never mind, never mind<br>"
                + "I'm okay with being by your side for<br> as long as I can hide<br>"
                + "What if I told you that I've fallen?<br><br>"
                + "What if I told you that I've fallen?<br>"
                + "A heart-shaped arrow through my chest<br>"
                + "I'll make your breakfast every morning<br>"
                + "And pick you up when you're a mess<br><br>"
                + "I know that it won't ever stop<br>"
                + "You know I'll be there when you call me<br> whether you like it or not<br>"
                + "Without a warning, now I'm falling for<br> this picture on my phone<br>"
                + "But don't mind me, I'm just falling,<br> I'll get back up on my own<br><br>"
                + "Please don't say my name, help me put out this flame<br>"
                + "I'd rather hold onto this feeling that<br> you don't even believe in<br>"
                + "What if I told you that I've fallen?<br><br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind, nevermind, nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind, nevermind, nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind, nevermind, nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind, nevermind, nevermind<br><br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Oh, nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Oh, nevermind<br>"
                + "What if I told you that I've fallen?<br>"
                + "Nevermind, I said nevermind<br>"
                + "I shouldn't tell you that I've fallen</center></html>";
    }
    
    public void lowkey(){
        lyrics = "<html><center>Wonder what I'll do<br>"
                + "When the cops come through<br>"
                + "And the whiskey's run out<br>"
                + "'Cause I've been looking at you<br>"
                + "Since half past two<br>"
                + "Wanna take this downtown<br>"
                + "This liquid courage<br>"
                + "Got me way too honest<br>"
                + "Put your phone on vibrate<br>"
                + "Let's catch a vibe babe<br>"
                + "While the sun's down<br><br>"
                + "Hush now, I know<br>"
                + "We're a little too f*cked up to stay still love<br>"
                + "Be as quiet as you can<br>"
                + "'Cause if anyone sees they'll just blow sh*t up<br>"
                + "I don't gotta know if you're taken<br>"
                + "I'll just let you know, bedroom's vacant<br>"
                + "No one's gotta know, just us and the moon<br>"
                + "Till the sun starts waking<br><br>"
                + "Up's the only direction I see<br>"
                + "As long as we keep this<br><br>"
                + "Low, low, low, low, low, low, low, lowkey<br>"
                + "You ain't even gotta lo-, lo-, lo-, lo-, lo-, lo-, lo-, love me<br>"
                + "Us in a king sized, keep it a secret<br>"
                + "Say I'm your queen, I don't wanna leave this<br>"
                + "Low, low, low, low, low, low, low, lowkey<br><br>"
                + "Wizard with words, tellin' me<br>"
                + "My energy's so bewitching<br>"
                + "So I'll go first<br>"
                + "There's an open bar<br>"
                + "Let's close this distance<br>"
                + "Oh-oh-oh, my<br>"
                + "Don't make me have to spell it all night<br><br>"
                + "I don't really give a f*ck<br>"
                + "'Bout all the \"he said, she said\" bullsh*t<br>"
                + "So pick your poison love<br>"
                + "Let's go somewhere a little more exclusive<br>"
                + "Take a shot, take a chance, take my hand boy<br>"
                + "Tension so intense like an asteroid<br>"
                + "Be discreet, gotta dodge all the tabloids<br><br>"
                + "Let's not think too much, there ain't no problems<br>"
                + "As long as we keep this<br><br>"
                + "Low, low, low, low, low, low, low, lowkey<br>"
                + "You ain't even gotta lo-, lo-, lo-, lo-, lo-, lo-, lo-, love me<br>"
                + "Us in a king sized, keep it a secret<br>"
                + "Say I'm your queen, I don't wanna leave this<br>"
                + "Low, low, low, low, low, low, low, lowkey</center></html>";
    }
    
    public void MaybeMaybe(){
        lyrics = "<html><center>Got no idea where I'm going<br>"
                + "I'm lost<br>"
                + "I guess it comes with having too much time<br>"
                + "She's got her mind where her heart should be<br>"
                + "And I use my heart where my mind is free<br><br>"
                + "And I<br>"
                + "I don't wanna think about it<br>"
                + "And I<br>"
                + "I don't wanna think about it<br><br>"
                + "'Cause I know how I feel<br>"
                + "And it's whole<br>"
                + "And it's real<br>"
                + "And I don't know if I should still keep on going<br><br>"
                + "'Cause I don't see the point in telling her I love her<br>"
                + "When I know it goes one ear and out the other<br>"
                + "She don't feel it the same way<br>"
                + "Well maybe, maybe as a friend<br>"
                + "But even then I know I'm all alone<br>"
                + "Got no one in the end<br><br>"
                + "My imagination wanders off<br>"
                + "Making up all kinds of scenes<br>"
                + "I know I'll never star in<br>"
                + "And I'm wondering what keeps me tied down<br>"
                + "I need some help<br>"
                + "Pull me back to the ground<br><br>"
                + "And I<br>"
                + "I don't wanna think about it<br>"
                + "And I<br>"
                + "I don't wanna think about it<br><br>"
                + "'Cause I know how I feel<br>"
                + "And it's whole<br>"
                + "And it's real<br>"
                + "And I don't know if I should still keep on going<br><br>"
                + "'Cause I don't see the point in telling her I love her<br>"
                + "When I know it goes one ear and out the other<br>"
                + "She don't feel it the same way<br>"
                + "Well maybe, maybe as a friend<br>"
                + "But even then I know I'm all alone<br>"
                + "Got no one in the end<br><br>"
                + "I don't know<br>"
                + "I don't know<br>"
                + "I don't know what keeps me going<br>"
                + "I don't see the point in<br>"
                + "I don't see the point in<br>"
                + "I don't see the point in<br><br>"
                + "'Cause I don't see the point in telling her I love her<br>"
                + "When I know it goes one ear and out the other<br>"
                + "She don't feel it the same way<br>"
                + "Well maybe, maybe as a friend<br>"
                + "But even then I know I'm all alone<br>"
                + "Got no one in the end</center></html>";
    }
    
    public void RunawayBaby(){
        lyrics = "<html><center>Ah, yes<br><br>"
                + "Well, looky here, looky here<br>"
                + "Ah, what do we have?<br>"
                + "Another pretty thang ready for me to grab<br>"
                + "But little does she know<br>"
                + "That I'm a wolf in sheep's clothing<br>"
                + "'Cause at the end of the night<br>"
                + "It is her I'll be holding<br><br>"
                + "I love you so<br>"
                + "That's what you'll say<br>"
                + "You'll tell me, \"Baby, baby, please don't go away\"<br>"
                + "But when I play<br>"
                + "I never stay<br>"
                + "To every girl that I meet, yeah, this is what I say<br><br>"
                + "\"Run, run, run away, run away, baby,<br>"
                + "Before I put my spell on you<br>"
                + "You better get, get, get away, get away, darling,<br>"
                + "'Cause everything you heard is true<br>"
                + "Your poor little heart will end up alone<br>"
                + "'Cause Lord knows I'm a rolling stone<br>"
                + "So, you better run, run, run away, run away, baby\"<br><br>"
                + "Well, let me think, let me think<br>"
                + "Ah, what should I do?<br>"
                + "So many eager young bunnies<br>"
                + "That I'd like to pursue<br>"
                + "Now even though they're eating<br> out the palm of my hand<br>"
                + "There's only one carrot<br>"
                + "And they all gotta share it!<br><br>"
                + "I love you so<br>"
                + "That's what you'll say<br>"
                + "You'll tell me, \"Baby, baby, please don't go away\"<br>"
                + "But when I play<br>"
                + "I never stay<br>"
                + "To every girl that I meet, yeah, this is what I say<br><br>"
                + "\"Run, run, run away, run away, baby,<br>"
                + "Before I put my spell on you<br>"
                + "You better get, get, get away, get away, darling,<br>"
                + "'Cause everything you heard is true<br>"
                + "Your poor little heart will end up alone<br>"
                + "'Cause Lord knows I'm a rolling stone<br>"
                + "So, you better run, run, run away, run away, baby\"<br><br>"
                + "Uh, check it out<br><br>"
                + "See, I ain't tryna hurt you, baby<br>"
                + "No, no, no, I just wanna work you, baby<br>"
                + "Yup, yup<br>"
                + "See, I ain't tryna hurt you, baby<br>"
                + "No, no, no, I just wanna work you, baby<br><br>"
                + "If you're scared you better run<br>"
                + "You better run,<br>"
                + "You better run,<br>"
                + "You better—, you better—, you better—<br><br>"
                + "Run, run, run away, run away, baby,<br>"
                + "Before I put my spell on you<br>"
                + "You better get, get, get away, get away, darling,<br>"
                + "'Cause everything you heard is true<br>"
                + "Your poor little heart will end up alone<br>"
                + "'Cause Lord knows I'm a rolling stone<br>"
                + "So, you better run, run, run away, run away, baby</center></html>";
    }
    
    public void Sanctuary(){
        lyrics = "<html><center>Go ahead and bark after dark, fallen star<br>"
                + "I'm your one-call away<br>"
                + "Motel halls, neon walls<br>"
                + "When night falls I am your escape<br>"
                + "When you lay alone, I ache<br>"
                + "Something I wanted to feel<br><br>"
                + "If you've been waiting for falling in love<br>"
                + "Babe, you don't have to wait on me<br>"
                + "'Cause I've been aiming for heaven above<br>"
                + "But an angel ain't what I need<br><br>"
                + "Not anyone, you're the one<br>"
                + "More than fun, you're the sanctuary<br>"
                + "'Cause what you want is what I want, sincerity<br><br>"
                + "Souls that dream alone lie awake<br>"
                + "I'll give you something so real<br><br>"
                + "If you've been waiting for falling in love<br>"
                + "Babe, you don't have to wait on me<br>"
                + "'Cause I've been aiming for heaven above<br>"
                + "But an angel ain't what I need<br><br>"
                + "Hold me oh so close, 'cause you never know<br>"
                + "Just how long our lives will be<br><br>"
                 + "If you've been waiting for falling in love<br>"
                + "Babe, you don't have to wait on me<br>"
                + "'Cause I've been aiming for heaven above<br>"
                + "But an angel ain't what I need</center></html>";
    }
    
    public void SheWillBeLoved(){
        lyrics = "<html><center>Beauty queen of only eighteen<br>"
                + "She had some trouble with herself<br>"
                + "He was always there to help her<br>"
                + "She always belonged to someone else<br><br>"
                + "I drove for miles and miles and wound up at your door<br>"
                + "I've had you so many times<br> but somehow I want more<br><br>"
                + "I don't mind spending every day<br>"
                + "Out on your corner in the pouring rain<br>"
                + "Look for the girl with the broken smile<br>"
                + "Ask her if she wants to stay a while<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br><br>"
                + "Tap on my window, knock on my door<br>"
                + "I want to make you feel beautiful<br>"
                + "I know I tend to get so insecure<br>"
                + "Doesn't matter anymore<br><br>"
                + "It's not always rainbows and butterflies<br>"
                + "It's compromise that moves us along, yeah<br>"
                + "My heart is full and my door's always open<br>"
                + "You come any time you want, yeah<br><br>"
                + "I don't mind spending every day<br>"
                + "Out on your corner in the pouring rain<br>"
                + "Look for the girl with the broken smile<br>"
                + "Ask her if she wants to stay a while<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br><br>"
                + "I know where you hide alone in your car<br>"
                + "Know all of the things that make you who you are<br>"
                + "I know that goodbye means nothing at all<br>"
                + "Comes back and makes me catch her<br> every time she falls<br>"
                + "Yeah<br><br>"
                + "Tap on my window, knock on my door<br>"
                + "I want to make you feel beautiful<br><br>"
                + "I don't mind spending every day<br>"
                + "Out on your corner in the pouring rain<br>"
                + "Look for the girl with the broken smile<br>"
                + "Ask her if she wants to stay a while<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br>"
                + "And she will be loved<br><br>"
                + "Please don't try so hard to say goodbye<br>"
                + "Please don't try so hard to say goodbye<br><br>"
                + "Out on your corner in the pouring rain<br><br>"
                + "Please don't try so hard to say goodbye</center></html>";
    }
}
